### ISSUE TITLE
Fingerprint Verification & QUIC Handshake

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#28]
My understanding of how the certificate verification seems to be different than what the spec infers. My understanding of the (simplified) handshake:
1) Possibly negotiate source address token
2) Client sends certificate to server & server verifies the certificate's fingerprint.
3) Server sends certificate to the client & client verifies the certificate's fingerprint.
4) Start sending encrypted data and exchange forward secure keys for future encryption

The spec seems to imply that the fingerprint verification is done after the handshake finishes:
_After the QUIC handshake exchange completes (but before the remote fingerprint is verified) incoming packets may be received._

From what I understand this is now how it works in WebRTC today. A callback is injected for certificate fingerprint verification that happens during the handshake. I believe this is how it will exist in QUIC as well once the TLS 1.3 handshake is supported.

Is it the intended behavior to verify the certificate after the handshake? If this isn't the case I believe we could take out this:
_A modest buffer MUST be provided to avoid loss of media prior to remote fingerprint validation_

**Comment by aboba** [comment]
The spec is assuming that the certificate fingerprints are being exchanged in signaling as they are with DTLS.  In DTLS, the fingerprint in the "a=fingerprint" line in SDP is compared with the calculated fingerprint of the certificate exchanged in the DTLS handshake.  As a result, in ORTC the ICE and DTLS handshakes can complete, and the Offerer may receive data or media prior to arrival of the Answer that enables the Answerer's fingerprint to be verified. 

Since this specification doesn't deal with media over QUIC, we probably don't need to talk about "loss of media".  However, I'm wondering if it's possible for QUIC data to be received prior to fingerprint verification.  If so, this probably shouldn't be passed to the application prior to verification.

**Comment by robin-raymond** [comment]
The real issue is that the transport can send data over the wire but the data must buffer remotely (up until the normal allowed buffering for readable data) EXCEPT the remote party cannot notify of any data being readable until the secure transport has been validated.

**Comment by juberti** [comment]
Is it possible for the DTLS handshake to complete before the answer is received? I don't think the offerer can send its ICE checks until it gets the answer (doesn't have ICE password of answerer), therefore it can't send the Server Hello in the DTLS handshake.

**Comment by aboba** [comment]
@Juberti In ORTC ICE and DTLS signaling can be separated, so some things are possible that can't happen in WebRTC 1.0.

For example, an Offerer can send ICE checks (and respond to incoming checks) as soon as it obtains the remote peer's ICE parameters and calls start().  Once the remote peer receives the local peer's ICE parameters, it can call start() and send checks.  After the remote ICE parameters are received by the local peer it can respond to checks and a response received by the remote peer enables the remote peer to begin the DTLS handshake. 

After the local peer receives the remote ICE parameters and calls start(), it can respond to the incoming DTLS handshake and negotiation can proceed.  However, the remote fingerprint cannot be verified until the DTLS remote parameters are received, so until then any media received cannot be rendered.

**Comment by juberti** [comment]
sure, but it still seems like a largely hypothetical problem. That is, if you can get the remote ICE params, you can probably get the fingerprint. Right?

**Comment by robin-raymond** [comment]
If it's ORTC there's no enforcement the DTLS fingerprint must have happened API wise prior to receiving the ICE data, but yes, it's unlikely someone will have not have the information needed. But we still have to describe what happens in this case because it's technically possible. The trouble is we can't tell on the "answer" side if the remote party has definitely validated their fingerprint to prevent data from being sent prior to validation. So the only thing we can do is decide on the receiving end what to do about data arriving where the fingerprint was not validated yet.

**Comment by juberti** [comment]
Agreed, buffering seems fine. My point was essentially that the solution doesn't need to be perfect given that this is a corner case.
