### ISSUE TITLE
createStream() triggering remote stream creation

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#55]
Currently there isn't any language about how the remote stream (onquicstream) is created. One would assume that this happens when you call createStream() on the local side, but this doesn't seem to be the case. According to the ietf spec ([section 9.2.2](https://tools.ietf.org/html/draft-ietf-quic-transport-14#section-9.2.2)):
 _"The receiving part of a stream initiated by a peer...are created when the first STREAM, STREAM_BLOCKED, RST_STREAM, or MAX_STREAM_DATA (bidirectional only, see below) is received for that stream. "_

This means that the remote stream isn't created until you write something to the remote side (a STREAM frame), although we don't mention this.

**Comment by pthatcherg** [comment]
If we create either a bidirectional or receive-only stream, would we send MAX_STREAM_DATA?  If so, we're covered for those.  Then what's left is if we create a send-only stream and don't write to it.  That's an interesting case.  On one hand, it would be surprising if onquicstream didn't get fired on the remote side.  On the other hand, what would you do with the incoming (receive only on the remote side)  stream if nothing is written to it?

Could it be possible to force and empty STREAM frame if nothing is written after some period (like 200ms) just so the other side knows the stream has been created?

**Comment by shampson** [comment]
Note: We should look at the spec and see if MAX_STREAM_DATA is required for bidirectional streams before sending STREAM frames. Also see if this is possible with current implementations.

**Comment by pthatcherg** [comment]
MAX_STREAM_DATA isn't allowed for receive-only streams.  So it won't work for createStream(send) because the remote side sees that as receive-only.

And a STREAM frame with length of 0 means "use the rest of the packet", which might work, but it wouldn't be sent reliably, so if that packet got lost, onquicstream wouldn't be fired.

None of the other packets which have a stream ID are allowed either.  So I think we're stuck either 

A.  Asking the QUIC protocol to add something (probably not going to happen)
B.  Adding our own protocol on top, like using up a QUIC stream to send QUIC stream IDs or using up a byte on each QUIC stream.  Both of these I would not want to do.
C.  Telling the developer it won't fire until the stream is written to.  It surprising, perhaps.  But maybe we could rename onquicstream to onreadablequicstream and making it clear that it only fires when a quic stream from the remote side is written to.

**Comment by shampson** [comment]
I'm okay with option C. here.

**Comment by shampson** [comment]
@aboba This is another issue I left open after [PR 70](https://github.com/w3c/webrtc-quic/pull/70). I went ahead with option C. here. Should we go ahead and close?

**Comment by aboba** [comment]
@shampson Since in the bi-directional case MAX_STREAM_DATA will be sent, shouldn't onbidirectionalstreamwithdata be onbidirectionalstream?

**Comment by shampson** [comment]
I guess that depends. I think for bidirectional streams QUIC _can_ send a MAX_STREAM_DATA frame to create the remote side stream. This is not currently supported in gQUIC. This frame is purely used inside the implementation for flow control limits. Event though this is possible, would we want to have different cases? For example as a web developer do I want the creation of a bidirectional stream to trigger a remote stream, while a send only stream does not? I don't know if the inconsistency between the two is the best thing to do.

**Comment by lgrahl** [comment]
In any case, I'd be in favour of truncating the event name. *With data* seems like an unnecessary information if there is no other event for *without data*.

**Comment by shampson** [comment]
Adding ready for PR label to update unnecessary naming. I think after that this issue can be closed.

**Comment by shampson** [comment]
I went back to PR 70 to look at the discussion around the new stream events. There wasn't consensus around the naming. The names would be either:
- Current naming: onreceivestreamwithdata / onbidirectionalstreamwithdata
- Alternative naming: onreceivestream / onbidirectionalstream

I don't have a strong opinion, but I'm fine removing "withdata" as long as it is clear that the remote stream is only created after sending data. 

Thoughts?
